version: '3.7'

services:
  mariadb:
    image: mariadb:10.6.7
    hostname: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: ${MARIADB_USERNAME}
      MYSQL_ROOT_PASSWORD: ${MARIADB_PASSWORD}
      MYSQL_DATABASE: ${MARIADB_DATABASE}
    networks:
      - messagequeue

  zookeeper:
    image: confluentinc/cp-zookeeper:6.1.4
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_MAXCLIENTCNXNS: 0
    networks:
      - messagequeue

  kafka:
    image: confluentinc/cp-kafka:6.1.4
    hostname: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - messagequeue

  kafka-ui:
    image: provectuslabs/kafka-ui:0.3.3
    hostname: kafka-ui
    ports:
      - "9021:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    depends_on:
      - zookeeper
      - kafka
    restart: always
    networks:
      - messagequeue

networks:
  messagequeue:
    name: messagequeue
    driver: bridge
